### ISSUE TITLE
Docker instructions not working.

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mscraftsman/devcon2023#2]
Tried

```
/devcon2023/$ docker-compose up -d
```

Got

```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
```

**Comment by renghen** [comment]
The docker-compose have been removed, it was to allowed development using docker instead of installing the packages natively namely php, lavarel, php compose etc.., it caused more problems than it was worth, so it was removed.
